NUM_BITS = 1024
NOISE_STD = 0.01
PATHLOSS_EXPONENT = 3.0
MIN_DISTANCE = 2.0
MAX_DISTANCE = 30.0
BURST_AMPLITUDE = 5
BURST_LENGTH = 12
THRESHOLD_K = 4

SENSING_ECHO_AMPLITUDE = 1.25
SENSING_DOPPLER_HZ = 0.08
SENSING_PHASE_RAD = 0.0
SENSING_DELAY = 0
SENSING_WINDOW_SIZE = 64
SENSING_WINDOW_STEP = 16
MIN_EVENT_SAMPLES = 3
ABNORMAL_DOPPLER_HZ = 0.22
NORMAL_DOPPLER_HZ = 0.015
ABNORMAL_DOPPLER_THRESHOLD_HZ = 0.12

STREAM_INTERVAL_SECONDS = 1.0
STREAM_FRAME_BITS = 256
STREAM_FALL_PROBABILITY = 0.08
STREAM_PATIENT_COUNT = 6

MONTE_CARLO_TRIALS = 50
